// <auto-generated />
using System;
using CondominioInteligente.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CondominioInteligente.Migrations
{
    [DbContext(typeof(CondominioInteligenteContext))]
    [Migration("20230429185426_Inclusaodeareacomum")]
    partial class Inclusaodeareacomum
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CondominioInteligente.Models.AreaComum", b =>
                {
                    b.Property<int>("CodArea")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodArea"));

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("UsuarioCodUsuario")
                        .HasColumnType("int");

                    b.HasKey("CodArea");

                    b.HasIndex("UsuarioCodUsuario");

                    b.ToTable("AreaComum");
                });

            modelBuilder.Entity("CondominioInteligente.Models.Usuario", b =>
                {
                    b.Property<int>("CodUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodUsuario"));

                    b.Property<int>("CodTipoUsuario")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CodUsuario");

                    b.ToTable("usuarios");
                });

            modelBuilder.Entity("CondominioInteligente.Models.AreaComum", b =>
                {
                    b.HasOne("CondominioInteligente.Models.Usuario", null)
                        .WithMany("AreaComums")
                        .HasForeignKey("UsuarioCodUsuario");
                });

            modelBuilder.Entity("CondominioInteligente.Models.Usuario", b =>
                {
                    b.Navigation("AreaComums");
                });
#pragma warning restore 612, 618
        }
    }
}
